#!/usr/bin/env node

var xmpp = require( 'simple-xmpp' ),
  spawn = require( 'child_process' ).spawn,
  args = require( 'optimist' )
    .usage( '$0 -j <jid> -p <password> [ -s <server>, -P <port>, -o <only allow from jid>]\n' )
    .demand( ['j','p'] )
    .argv,
  cmd = "task";

function say( to, args ) {
  var t = spawn( cmd, args ), proc;

  t.stdout.on( 'data', function( data ) {
    xmpp.send( to, data.toString() );
  });

  t.on( 'error', function( error ) {
    throw error;
  });

  t.on( 'exit', function( stat ) {
    clearTimeout( proc );
  });

  proc  = setTimeout( function() {
    t.kill( 'SIGHUP' );
  }, 3000 );
}

xmpp.on( 'chat', function( from, message ) {
  var a = message.split( ' ' );
  if ( args.o ) {
   if (  args.o === from ) {
      say( from, a );
    } else {
      console.log( 'unknown command from %s', from );
    }
  } else {
    say( from, a );
  }
});

xmpp.on( 'online', function() {
  console.log( 'connected' );
});

xmpp.on( 'buddy', function( jid, state ) {
});

xmpp.on( 'stanza', function( stanza ) {
});

xmpp.on( 'error', function( error ) {
  throw error;
});

xmpp.connect( {
  jid: args.j,
  password: args.p,
  host: args.s,
  port: args.P || 5222
});

// vim:ft=javascript et :
